#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "🔒 Requesting super-user privileges..."
    exec sudo "$0" "$@"
    exit 1
fi

# Function to enable Conservation Mode(Used wildcards 'cuz the digits after VPC differ on different variants of the same model)
enable_conservation() {
    echo 1 > /sys/bus/platf*/drivers/ideap*/VPC*/conser*
    echo "✅ Conservation Mode has been enabled."
}
disable_conservation() {
    echo 0 > /sys/bus/platf*/drivers/ideap*/VPC*/conser*
    echo "❌ Conservation Mode has been disabled."
}

# Function Lock
enable_fn_lock() {
    echo 1 > /sys/bus/platf*/drivers/ideap*/VPC*/fn*
    echo "✅ Function Lock has been enabled."
}
disable_fn_lock() {
    echo 0 > /sys/bus/platf*/drivers/ideap*/VPC*/fn*
    echo "❌ Function Lock has been disabled."
}

# To display the menu
echo "QuickVantage - Lenovo Utility"
echo "============================="
echo "1) Enable Conservation Mode"
echo "2) Enable Function Lock"
echo "3) Enable Both"
echo "============================="

read -p "Choose an option (1-3): " choice

# Case for processing the user-input
case $choice in
    1)
        enable_conservation
        ;;
    2)
        enable_fn_lock
        ;;
    3)
        enable_conservation
        enable_fn_lock
        ;;
    *)
        echo "❌ Invalid option. Exiting."
        exit 1
        ;;
esac
